# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('drinkID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=150)),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('foodID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=150)),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
